### ISSUE TITLE
Party Rando Fails on Seed 11900

### ISSUE THREAD

**Issue by LaneDibello** [LaneDibello/Kotor-Randomizer-2#42] opened 2021-03-06 22:53 UTC
When attempting to do a party randomization with seed set to 11900, we encounter a caught "Object reference not set to an instance of an object" exception. I have not yet have time to dig into this, so I'm just leaving the means to replicate the issue here.

**Comment by glasnonck** [comment] 2021-03-07 04:47
I wasn't able to replicate the issue myself with just the seed 11900. I tried party randomization with each "Other" randomization option except name generation, as I don't know what names you may have set up. Could you replicate the issue on your end and maybe send me the "current.krp" file so I know all of your settings (or just list the enabled features)?

**Comment by glasnonck** [comment] 2021-03-07 04:57
On further investigation, the issue is only on the old branch that was merged in #39, not on the fully merged branch. The issue is that Zaalbar is being replaced with "sebulba," which is one of the broken characters. This issue was handled in issue #35, which was handled in a separate branch, and is now merged as of #38. As such, I'll close this issue. Feel free to re-open it if you replicate the issue on the current master branch.

**Closed by glasnonck** 2021-03-07 04:57 UTC
Labels: bug
